@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Dec 26 22:08:55 -0500 2023
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim iserdes_1_time_impl -key {Post-Implementation:sim_1:Timing:iserdes_1} -tclbatch iserdes_1.tcl -view D:/P_vhdl_Vi/ADC_AFE_SERDES/adcClock_FclkFrm_simul1.wcfg -log simulate.log"
call xsim  iserdes_1_time_impl -key {Post-Implementation:sim_1:Timing:iserdes_1} -tclbatch iserdes_1.tcl -view D:/P_vhdl_Vi/ADC_AFE_SERDES/adcClock_FclkFrm_simul1.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
